using Newtonsoft.Json;
using UniPresence.Types.Presence.Types.Action;
using UniPresence.Types.Presence.Types.Music;

namespace UniPresence.Types.Presence;

[JsonObject]
public class ApiApplicationPresence
{
    /// <summary>
    /// The info for the application this presence is coming from
    /// </summary>
    public ApiApplicationInfo ApplicationInfo { get; set; }
    
    /// <summary>
    /// A list of music presences generated by this application
    /// </summary>
    public List<ApiMusicPresence> MusicPresences { get; set; }
    /// <summary>
    /// A list of action presences generated by this application
    /// </summary>
    public List<ApiActionPresence> ActionPresences { get; set; }
}